### ISSUE TITLE
Connection refused to DB when running application

### ISSUE THREAD

**Issue by Kai-Striega** [kalicialopez/mentorme#1]
Hello.

I'm trying to set up the project by following the instructions in the README. This occurs with both with ``uv run manage.py migrate`` and by using the docker compose file (``docker compose up``). The log is:

```
Traceback (most recent call last):
  File "/home/kai/Projects/mentorme/.venv/lib/python3.12/site-packages/django/db/backends/base/base.py", line 279, in ensure_connection
    self.connect()
  File "/home/kai/Projects/mentorme/.venv/lib/python3.12/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kai/Projects/mentorme/.venv/lib/python3.12/site-packages/django/db/backends/base/base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kai/Projects/mentorme/.venv/lib/python3.12/site-packages/django/contrib/gis/db/backends/postgis/base.py", line 126, in get_new_connection
    connection = super().get_new_connection(conn_params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kai/Projects/mentorme/.venv/lib/python3.12/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kai/Projects/mentorme/.venv/lib/python3.12/site-packages/django/db/backends/postgresql/base.py", line 332, in get_new_connection
    connection = self.Database.connect(**conn_params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kai/Projects/mentorme/.venv/lib/python3.12/site-packages/psycopg/connection.py", line 119, in connect
    raise last_ex.with_traceback(None)
psycopg.OperationalError: connection failed: connection to server at "127.0.0.1", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
```

@kalicialopez is this the same error you were getting?

**Comment by bendog** [comment]
are you running it locally? 
do you have postgres up and running?

**Comment by Kai-Striega** [comment]
This occurs for both locally and docker.

**Comment by bendog** [comment]
are you using the latest main? 
it should not be trying to connect to 127.0.0.1 on docker compose?

<img width="594" alt="image" src="https://github.com/user-attachments/assets/a73b68fd-2d16-44ff-9730-1d496e5d5c0b" />

**Comment by bendog** [comment]
if you are running it locally you will need to run `docker-compose up db` to make sure the database is actually running and connectable

**Comment by Kai-Striega** [comment]
It doesn't look like that works:

```shell
(mentorme) kai@kai-MS-7D32:~/Projects/mentorme$ docker compose up db
Attaching to db-1
Gracefully stopping... (press Ctrl+C again to force)
Error response from daemon: driver failed programming external connectivity on endpoint mentorme-db-1 (b263c39c4d9242cf31df8b4c1dc37593aedff6450a78f8435f7f4170bf284014): failed to bind port 0.0.0.0:5432/tcp: Error starting userland proxy: listen tcp4 0.0.0.0:5432: bind: address already in use
```

**Comment by bendog** [comment]
do you already have postgres running on 5432?

**Comment by Kai-Striega** [comment]
This occurred due to the web service being built before the database was ready. It has been fixed in this [commit](https://github.com/kalicialopez/mentorme/commit/463f991275b5a09558fd325fba91fe992722e8f1)
